A <- read.table ("./riborf/corrected/read.dist.sample.1.txt", sep="\t")
loc1 <- c(-30:50)
loc2 <- c(-50:30)
B1 <- apply(A[1,2:ncol(A)], 2, sum)
B2 <- apply(A[2,2:ncol(A)], 2, sum)
pdf (file="./riborf/corrected/plot.readDist.1.pdf")
par(mfrow=c(2,2), mar=c(2,2,2,1))
plot(loc1, B1, xlim=c(-20, 30),  type="h", lwd=2, ylim=c(0,max(c(B1,B2))), main=1, xlab="Flanking start codon")
abline (v=-20, col=8, lwd=1, lty="dotted")
abline (v=-10, col=8, lwd=1, lty="dotted")
abline (v=0, col=8, lwd=1,  lty="dotted")
abline (v=10, col=8, lwd=1,  lty="dotted")
abline (v=20, col=8, lwd=1,  lty="dotted")
abline (v=30, col=8, lwd=1,  lty="dotted")
plot(loc2, B2, xlim=c(-30, 20), type="h", lwd=2, ylim=c(0,max(c(B1,B2))), main=1, xlab="Flanking stop codon")
abline (v=-30, col=8, lwd=1, lty="dotted")
abline (v=-20, col=8, lwd=1, lty="dotted")
abline (v=-10, col=8, lwd=1, lty="dotted")
abline (v=0, col=8, lwd=1,  lty="dotted")
abline (v=10, col=8, lwd=1,  lty="dotted")
abline (v=20, col=8, lwd=1,  lty="dotted")
dev.off()
